export type ComponentEntry = {
  name: string;
  file: string;
  description: string;
  dependencies: string[];
  registryDependencies: string[];
  tier: 1 | 2 | 3;
};

export const registry: Record<string, ComponentEntry> = {
  button: {
    name: "Button",
    file: "components/ui/button.tsx",
    description: "A pressable button with variants",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  text: {
    name: "Text",
    file: "components/ui/text.tsx",
    description: "Typography with heading and body variants",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  input: {
    name: "Input",
    file: "components/ui/input.tsx",
    description: "Text input with variants and states",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  textarea: {
    name: "Textarea",
    file: "components/ui/textarea.tsx",
    description: "Multi-line text input",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  card: {
    name: "Card",
    file: "components/ui/card.tsx",
    description: "Card container with header, content, footer",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: ["text"],
    tier: 1,
  },
  badge: {
    name: "Badge",
    file: "components/ui/badge.tsx",
    description: "Small status indicator",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  separator: {
    name: "Separator",
    file: "components/ui/separator.tsx",
    description: "Visual divider",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  avatar: {
    name: "Avatar",
    file: "components/ui/avatar.tsx",
    description: "User avatar with image and fallback",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  alert: {
    name: "Alert",
    file: "components/ui/alert.tsx",
    description: "Alert message with variants",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  label: {
    name: "Label",
    file: "components/ui/label.tsx",
    description: "Form field label",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  skeleton: {
    name: "Skeleton",
    file: "components/ui/skeleton.tsx",
    description: "Animated loading placeholder",
    dependencies: ["react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 2,
  },
  switch: {
    name: "Switch",
    file: "components/ui/switch.tsx",
    description: "Toggle switch",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  checkbox: {
    name: "Checkbox",
    file: "components/ui/checkbox.tsx",
    description: "Checkbox with checked state",
    dependencies: ["@rn-primitives/checkbox", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 3,
  },
  "radio-group": {
    name: "RadioGroup",
    file: "components/ui/radio-group.tsx",
    description: "Radio button group",
    dependencies: ["@rn-primitives/radio-group", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 3,
  },
  progress: {
    name: "Progress",
    file: "components/ui/progress.tsx",
    description: "Progress bar",
    dependencies: ["@rn-primitives/progress", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 3,
  },
  spinner: {
    name: "Spinner",
    file: "components/ui/spinner.tsx",
    description: "Loading spinner with sizes",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  list: {
    name: "List",
    file: "components/ui/list.tsx",
    description: "Styled list items",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  accordion: {
    name: "Accordion",
    file: "components/ui/accordion.tsx",
    description: "Expandable content sections",
    dependencies: ["@rn-primitives/accordion", "react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: ["animate"],
    tier: 3,
  },
  tabs: {
    name: "Tabs",
    file: "components/ui/tabs.tsx",
    description: "Tab navigation with filled/line variants, sizes, vertical, disabled, and icon support",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  collapsible: {
    name: "Collapsible",
    file: "components/ui/collapsible.tsx",
    description: "Animated show/hide content",
    dependencies: ["react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: ["animate"],
    tier: 2,
  },
  toast: {
    name: "Toast",
    file: "components/ui/toast.tsx",
    description: "Notification toast with auto-dismiss, position (top/bottom), and slide-in direction (top/bottom/left/right)",
    dependencies: ["@rn-primitives/portal", "react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: ["animate"],
    tier: 3,
  },
  dialog: {
    name: "Dialog",
    file: "components/ui/dialog.tsx",
    description: "Modal dialog overlay",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "alert-dialog": {
    name: "AlertDialog",
    file: "components/ui/alert-dialog.tsx",
    description: "Confirmation dialog with actions",
    dependencies: ["react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: ["animate"],
    tier: 2,
  },
  tooltip: {
    name: "Tooltip",
    file: "components/ui/tooltip.tsx",
    description: "Accessible tooltip with positioning",
    dependencies: ["@rn-primitives/tooltip", "@rn-primitives/portal", "react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: ["animate"],
    tier: 3,
  },
  popover: {
    name: "Popover",
    file: "components/ui/popover.tsx",
    description: "Contextual overlay with trigger positioning",
    dependencies: ["@rn-primitives/popover", "@rn-primitives/portal", "react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: ["animate"],
    tier: 3,
  },
  "bottom-sheet": {
    name: "BottomSheet",
    file: "components/ui/bottom-sheet.tsx",
    description: "Bottom sheet overlay",
    dependencies: ["@gorhom/bottom-sheet", "react-native-gesture-handler", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 3,
  },
  "action-sheet": {
    name: "ActionSheet",
    file: "components/ui/action-sheet.tsx",
    description: "Action sheet with options",
    dependencies: ["@gorhom/bottom-sheet", "react-native-gesture-handler", "clsx", "tailwind-merge"],
    registryDependencies: ["bottom-sheet"],
    tier: 3,
  },
  select: {
    name: "Select",
    file: "components/ui/select.tsx",
    description: "Dropdown select with search support",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  calendar: {
    name: "Calendar",
    file: "components/ui/calendar.tsx",
    description: "Month calendar with single and range selection",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "date-picker": {
    name: "DatePicker",
    file: "components/ui/date-picker.tsx",
    description: "Date picker with calendar popup and range support",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: ["calendar"],
    tier: 1,
  },
  slider: {
    name: "Slider",
    file: "components/ui/slider.tsx",
    description: "Draggable slider for numeric values",
    dependencies: ["react-native-gesture-handler", "react-native-reanimated", "class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 2,
  },
  toggle: {
    name: "Toggle",
    file: "components/ui/toggle.tsx",
    description: "Two-state toggle button",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "toggle-group": {
    name: "ToggleGroup",
    file: "components/ui/toggle-group.tsx",
    description: "Group of exclusive toggle buttons",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: ["toggle"],
    tier: 1,
  },
  drawer: {
    name: "Drawer",
    file: "components/ui/drawer.tsx",
    description: "Slide-in side navigation panel",
    dependencies: ["react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: ["animate"],
    tier: 2,
  },
  "input-otp": {
    name: "InputOTP",
    file: "components/ui/input-otp.tsx",
    description: "One-time password input with individual cells",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  table: {
    name: "Table",
    file: "components/ui/table.tsx",
    description: "Data table with header, body, rows, and cells",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "search-bar": {
    name: "SearchBar",
    file: "components/ui/search-bar.tsx",
    description: "Search input with icon, clear button, and cancel",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  chip: {
    name: "Chip",
    file: "components/ui/chip.tsx",
    description: "Interactive tag for filters and multi-select",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  fab: {
    name: "FAB",
    file: "components/ui/fab.tsx",
    description: "Floating action button for primary screen actions",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "empty-state": {
    name: "EmptyState",
    file: "components/ui/empty-state.tsx",
    description: "Placeholder for empty screens and error states",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "dropdown-menu": {
    name: "DropdownMenu",
    file: "components/ui/dropdown-menu.tsx",
    description: "Dropdown menu with items, separators, and destructive actions",
    dependencies: ["@rn-primitives/dropdown-menu", "@rn-primitives/portal", "react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: ["animate"],
    tier: 3,
  },
  "context-menu": {
    name: "ContextMenu",
    file: "components/ui/context-menu.tsx",
    description: "Long-press context menu with items and separators",
    dependencies: ["@rn-primitives/context-menu", "@rn-primitives/portal", "react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: ["animate"],
    tier: 3,
  },
  image: {
    name: "Image",
    file: "components/ui/image.tsx",
    description: "Image with loading placeholder, error fallback, and rounded variants",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "segmented-control": {
    name: "SegmentedControl",
    file: "components/ui/segmented-control.tsx",
    description: "iOS-style segmented control for view switching",
    dependencies: [],
    registryDependencies: [],
    tier: 1,
  },
  carousel: {
    name: "Carousel",
    file: "components/ui/carousel.tsx",
    description: "Horizontal scrollable carousel with pagination dots",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  rating: {
    name: "Rating",
    file: "components/ui/rating.tsx",
    description: "Star rating with interactive and read-only modes",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  stepper: {
    name: "Stepper",
    file: "components/ui/stepper.tsx",
    description: "Numeric increment/decrement control with min/max/step",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  banner: {
    name: "Banner",
    file: "components/ui/banner.tsx",
    description: "Full-width notification banner with variants and dismiss",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "chart-tooltip": {
    name: "ChartTooltip",
    file: "components/ui/chart-tooltip.tsx",
    description: "Tooltip overlay for chart data points",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "area-chart": {
    name: "AreaChart",
    file: "components/ui/area-chart.tsx",
    description: "SVG area chart with gradient fill and grid",
    dependencies: ["react-native-svg", "clsx", "tailwind-merge"],
    registryDependencies: ["chart-tooltip"],
    tier: 3,
  },
  "bar-chart": {
    name: "BarChart",
    file: "components/ui/bar-chart.tsx",
    description: "Vertical and horizontal bar chart",
    dependencies: ["react-native-svg", "clsx", "tailwind-merge"],
    registryDependencies: ["chart-tooltip"],
    tier: 3,
  },
  "line-chart": {
    name: "LineChart",
    file: "components/ui/line-chart.tsx",
    description: "Multi-series line chart with data points",
    dependencies: ["react-native-svg", "clsx", "tailwind-merge"],
    registryDependencies: ["chart-tooltip"],
    tier: 3,
  },
  "pie-chart": {
    name: "PieChart",
    file: "components/ui/pie-chart.tsx",
    description: "Pie and donut chart with segments",
    dependencies: ["react-native-svg", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 3,
  },
  "radar-chart": {
    name: "RadarChart",
    file: "components/ui/radar-chart.tsx",
    description: "Radar/spider chart with polygon grid",
    dependencies: ["react-native-svg", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 3,
  },
  "radial-chart": {
    name: "RadialChart",
    file: "components/ui/radial-chart.tsx",
    description: "Circular radial progress chart",
    dependencies: ["react-native-svg", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 3,
  },
  "swipeable-list-item": {
    name: "SwipeableListItem",
    file: "components/ui/swipeable-list-item.tsx",
    description: "Swipeable list item revealing action buttons on swipe",
    dependencies: ["react-native-reanimated", "react-native-gesture-handler", "clsx", "tailwind-merge"],
    registryDependencies: ["animate"],
    tier: 3,
  },
  form: {
    name: "Form",
    file: "components/ui/form.tsx",
    description: "Form context with validation, error handling, and compound components",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: ["label", "text"],
    tier: 1,
  },
  "password-input": {
    name: "PasswordInput",
    file: "components/ui/password-input.tsx",
    description: "Password input with show/hide toggle and strength indicator",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: ["input"],
    tier: 1,
  },
  "theme-provider": {
    name: "ThemeProvider",
    file: "components/ui/theme-provider.tsx",
    description: "Theme context provider with light/dark/system mode and toggle",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "safe-area": {
    name: "SafeArea",
    file: "components/ui/safe-area.tsx",
    description: "Styled SafeAreaView wrapper with theme variants",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge", "react-native-safe-area-context"],
    registryDependencies: [],
    tier: 1,
  },
  header: {
    name: "Header",
    file: "components/ui/header.tsx",
    description: "Navigation header with back button, title, and right actions",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "tab-bar": {
    name: "TabBar",
    file: "components/ui/tab-bar.tsx",
    description: "Bottom tab bar with badge support and active states",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: ["badge", "text"],
    tier: 1,
  },
  "status-indicator": {
    name: "StatusIndicator",
    file: "components/ui/status-indicator.tsx",
    description: "Colored dot for online/offline/away/busy status",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "labeled-separator": {
    name: "LabeledSeparator",
    file: "components/ui/labeled-separator.tsx",
    description: "Horizontal separator with centered text label",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: ["separator"],
    tier: 1,
  },
  "masked-input": {
    name: "MaskedInput",
    file: "components/ui/masked-input.tsx",
    description: "Text input with mask formatting for credit cards, phones, dates",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: ["input"],
    tier: 1,
  },
  "phone-input": {
    name: "PhoneInput",
    file: "components/ui/phone-input.tsx",
    description: "Phone number input with country code selector",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: ["input", "masked-input"],
    tier: 1,
  },
  "number-input": {
    name: "NumberInput",
    file: "components/ui/number-input.tsx",
    description: "Numeric input with increment/decrement buttons and min/max",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  combobox: {
    name: "Combobox",
    file: "components/ui/combobox.tsx",
    description: "Searchable select with multi-select, groups, clear, and custom rendering",
    dependencies: ["react-native-svg", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "progress-steps": {
    name: "ProgressSteps",
    file: "components/ui/progress-steps.tsx",
    description: "Multi-step progress indicator for wizards and onboarding",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  timeline: {
    name: "Timeline",
    file: "components/ui/timeline.tsx",
    description: "Vertical timeline for events, order tracking, activity feeds",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "chat-bubble": {
    name: "ChatBubble",
    file: "components/ui/chat-bubble.tsx",
    description: "Message bubble for chat with sent/received variants and status",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "stat-card": {
    name: "StatCard",
    file: "components/ui/stat-card.tsx",
    description: "KPI display card with value, trend indicator, and change percentage",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: ["card"],
    tier: 1,
  },
  grid: {
    name: "Grid",
    file: "components/ui/grid.tsx",
    description: "FlatList-based grid layout with configurable columns and gap",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  price: {
    name: "Price",
    file: "components/ui/price.tsx",
    description: "Formatted currency display with locale and strikethrough support",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "refresh-control": {
    name: "RefreshControl",
    file: "components/ui/refresh-control.tsx",
    description: "Themed pull-to-refresh control for ScrollView and FlatList",
    dependencies: [],
    registryDependencies: [],
    tier: 1,
  },
  "infinite-list": {
    name: "InfiniteList",
    file: "components/ui/infinite-list.tsx",
    description: "FlatList with auto-loading more items on scroll",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: ["spinner"],
    tier: 1,
  },
  pagination: {
    name: "Pagination",
    file: "components/ui/pagination.tsx",
    description: "Page navigation with numbered buttons and prev/next",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: ["button"],
    tier: 1,
  },
  "file-picker": {
    name: "FilePicker",
    file: "components/ui/file-picker.tsx",
    description: "File upload UI with dashed border, preview, and remove button",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "connection-banner": {
    name: "ConnectionBanner",
    file: "components/ui/connection-banner.tsx",
    description: "Animated banner showing online/offline connection status",
    dependencies: ["react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: ["animate"],
    tier: 2,
  },
  "typing-indicator": {
    name: "TypingIndicator",
    file: "components/ui/typing-indicator.tsx",
    description: "Animated typing dots for chat interfaces",
    dependencies: ["react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 2,
  },
  "image-gallery": {
    name: "ImageGallery",
    file: "components/ui/image-gallery.tsx",
    description: "Horizontal image carousel with fullscreen modal and pagination",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: ["image"],
    tier: 1,
  },
  field: {
    name: "Field",
    file: "components/ui/field.tsx",
    description: "Layout-focused form field with label, description, and error",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "input-group": {
    name: "InputGroup",
    file: "components/ui/input-group.tsx",
    description: "Compose inputs with addons, buttons, text, and focus-aware container",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  kbd: {
    name: "Kbd",
    file: "components/ui/kbd.tsx",
    description: "Keyboard key display with grouping and separator",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "hover-card": {
    name: "HoverCard",
    file: "components/ui/hover-card.tsx",
    description: "Preview content card triggered by hover or long-press",
    dependencies: ["@rn-primitives/hover-card", "@rn-primitives/portal", "react-native-reanimated", "clsx", "tailwind-merge"],
    registryDependencies: ["animate"],
    tier: 3,
  },
  "direction-provider": {
    name: "DirectionProvider",
    file: "components/ui/direction-provider.tsx",
    description: "RTL/LTR direction context with I18nManager integration",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  animate: {
    name: "Animate",
    file: "components/ui/animate.tsx",
    description: "Animation presets, spring configs, easing, and hooks for Reanimated 4",
    dependencies: ["react-native-reanimated"],
    registryDependencies: [],
    tier: 2,
  },
  "data-table": {
    name: "DataTable",
    file: "components/ui/data-table.tsx",
    description: "Sortable, filterable data table with pagination and custom cell rendering",
    dependencies: ["react-native-svg", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
  "command-menu": {
    name: "CommandMenu",
    file: "components/ui/command-menu.tsx",
    description: "Spotlight-style searchable command palette with groups and keyboard shortcuts",
    dependencies: ["react-native-svg", "clsx", "tailwind-merge"],
    registryDependencies: [],
    tier: 1,
  },
};

export function getComponentNames(): string[] {
  return Object.keys(registry).sort();
}

export function resolveRegistryDeps(names: string[]): string[] {
  const resolved = new Set<string>();
  const queue = [...names];

  while (queue.length > 0) {
    const name = queue.pop()!;
    if (resolved.has(name)) continue;
    resolved.add(name);

    const entry = registry[name];
    if (entry) {
      for (const dep of entry.registryDependencies) {
        if (!resolved.has(dep)) {
          queue.push(dep);
        }
      }
    }
  }

  return Array.from(resolved);
}
